version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: familyfork_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: familyfork
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - familyfork_network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Backend API
  backend:
    build: ./backend
    container_name: familyfork_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/familyfork
      - DB_NAME=familyfork
      - CORS_ORIGINS=http://localhost:3000
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      - mongo
    networks:
      - familyfork_network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Frontend Application
  frontend:
    build: ./frontend
    container_name: familyfork_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - familyfork_network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: familyfork_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - familyfork_network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local

networks:
  familyfork_network:
    driver: bridge
